 # Database
database:
  url: jdbc:postgresql://localhost:5432/monitoring-service
  username: admin
  password: 12345
  schema: monitoring_service
  sizePool: 5
  test:
    version: 15
    username: test
    password: test
    name: monitoring_service
    schema: test

  
  # Liquibase
liquibase:
  change_log: db/changelog/changelog.yaml
  schema: liquibase
  test:
    schema: test
    change_log: db/changelog/changelog.yaml
  
  # JWT
jwt:
   secretKey: iJ39OWp+T+T07pDMI6DC75D5Z+mmLBbcSeWvY2uObX0=
   duration:
     access: 30
     refresh: 120